# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 10:57
from __future__ import unicode_literals

import BusManage.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date')),
                ('busNum', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('arrivalTime', models.CharField(max_length=10)),
                ('departureTime', models.CharField(max_length=10)),
                ('seatsAvailable', models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNo', models.CharField(blank=True, default='Volvo', max_length=15)),
                ('capacity', models.IntegerField(blank=True, default=180)),
                ('registrationNumber', models.CharField(blank=True, default=633116, max_length=6, unique=True)),
                ('companyName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OperatedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusManage_Buses_busNum', to='BusManage.Buses')),
                ('dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusManage_Buses_date', to='BusManage.Buses')),
                ('registrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30, validators=[BusManage.models.verify_email])),
                ('PhoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('FirstName', models.CharField(max_length=30, validators=[BusManage.models.validateName])),
                ('LastName', models.CharField(blank=True, max_length=30, validators=[BusManage.models.validateName])),
                ('Sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Age', models.IntegerField(validators=[BusManage.models.validate_age])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR', models.CharField(blank=True, default='GTQwvq', max_length=6)),
                ('price', models.CharField(default=809, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='pnrNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.Ticket'),
        ),
        migrations.AddField(
            model_name='issuedfor',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.Ticket', unique=True),
        ),
        migrations.AddField(
            model_name='issuedfor',
            name='busNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.Buses'),
        ),
        migrations.AddField(
            model_name='buses',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.Company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='PNR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManage.Ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='operatedby',
            unique_together=set([('busNum', 'dt')]),
        ),
        migrations.AlterUniqueTogether(
            name='buses',
            unique_together=set([('busNum', 'date')]),
        ),
    ]
