# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registrationNumber',
            field=models.CharField(blank=True, default=953218, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='v9LsQG', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=962, max_length=10),
        ),
    ]
