# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManage', '0003_auto_20170409_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registrationNumber',
            field=models.CharField(blank=True, default=213713, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='PNR',
            field=models.CharField(blank=True, default='6yjSeH', max_length=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.CharField(default=344, max_length=10),
        ),
    ]
